package POMCE;

public class PerformInspectionUtils {

	public static String performInsButton = "//button[text()='Perform Inspection']";
	public static String continueBtn = "//div[@class='footer_actions']/button[2]";
	public static String globalValidMsg = "//div[@class='case-inspection__global-error']/h2";
	public static String titlePIPage = "//div[@class='perform-inspection__title-text']/h1";
	public static String addVioPI = "//div[@id='case-inspection']//input";
	public static String selectVioList = "//div[@id='case-inspection']//div[@class='list-label']";
	public static String invalidBtnList = "//div[@class='multi-choice-buttons']/button[text()='Invalid']";
	public static String noteField = "//textarea[@placeholder='Enter Note']";
	public static String footerButtons = "//div[@class='footer_actions']/button";
	public static String addImgIcon = "//div[@class='case__attachment__title']/button";
	public static String browseFileLink = "//div[@class='attachments-modal__drag-drop-box']/label";
	public static String addBtnAttach = "//div[@class='attachments-modal__footer']/button[2]";
	public static String caseVioList = "//div[@class='case-details__violation-tile']/following::div[@class='case-violation-list']";
	public static String confirmationPopup = "//div[@class='disclaimer-modal__disclaimer-img']";
	public static String cancelConfirmation = "//div[@class='flex-row--center']/button[text()='Cancel']";
	public static String closeCasePopup = "//div[@class='modal-header' and text()='Close Case']";
	public static String modalHeaderPI = "//div[@class='modal-header']";
	public static String validBtnList = "//div[@class='multi-choice-buttons']/button[text()='Valid']";
	public static String voluntaryToggle = "//div[@class='multi-choice-buttons']/button[text()='Voluntary']";
	public static String cancelCloseCase = "//div[@class='modal-footer']//button[text()='Cancel']";
	public static String issueNoticeBtn = "//div[@class='progressive-form__footer']/button";
	public static String editVerifyVio = "//h2[text()='Verify Violations']/preceding-sibling::div";
	public static String editVioIcon = "//div[@class='case-inspection__violation-tile ']//div[@class='edit-entity__button-wrapper']/button";
	public static String editVioPopup = "//div[@id='case-inspection']//following::div[@class='modal-header']";
	public static String noNoticeToggleButton = "//button[text()='No Notice']";
	public static String noticeIssueDate = "//input[@name='issuedAt']";
	public static String cancelEditAnimal = "//div[@class='entity-modal__footer']/button[text()='Cancel']";
	public static String labelVioStatus1 = "//div/h2[text()='Verify Violations']/following-sibling::label";
	public static String vioVerificationStatus = "//div[@class='case-violation__status verification-pending']/label";
	public static String titleSection2 = "//h2[text()='Select Notice & Schedule Follow Up']";
	public static String forcedToggle = "//div[@class='multi-choice-buttons']/button[text()='Forced']";
	public static String closedInvalidStatus = "//div[@class='case-violation__status closed']";
	public static String openCompliantStatus = "//div[@class='case-violation__status open']";
	public static String noticeSelected = "//div[@class='notice-list row']//button";
	public static String noticeSelected2 = "(//div[@class='notice-list row']//button)[2]";
	public static String selectANotice = "(//div[@class='multi-choice-buttons'])[5]/button";
	public static String notice2 = "//div[@class='notice-list row']//button[2]";
	public static String titleSection3 = "//h2[text()='Generate Notice']";
	public static String noticeDatePicker = "//td[@class='rdtDay rdtActive rdtToday']/following::td[2]";
	public static String issueNoticeButton = "//button[text()='Issue Notice & Complete Inspection']";
	public static String continueBtnSec2 = "//div[@class='progressive-form active']//button[text()='Continue']";
	public static String vioListSec2 = "//div[@class='progressive-form active']//div[@class='case-violation-list']";
	public static String complyByDateFld = "(//input[@name='complyByDate'])[1]";
	public static String complyByDatePicker = "(//td[@class='rdtDay rdtActive']/following-sibling::td)[5]";
	public static String inspectionDateFld = "//input[@name='inspectionPlannedDate']";
	public static String inspectionDatePicker = "//input[@name='inspectionPlannedDate']//following::td[@class='rdtDay rdtActive']//following::td[2]";
	public static String agencyAdmin = "//label[@title='Follow-up inspection date']//following::button[1]";
	public static String certifiedMail = "//label[@title='Certified Mail Number']";
	public static String certifiedMailFld = "//input[@name='certifiedMailNumber']";
	public static String recipientTile = "//div[@class='recipient-tile-headline']";
	public static String recipientContacts = "//div[@class='recipient-tile__subtile']//span[@class='contact-name']";
	public static String generateNoticeBtn = "//div[@class='progressive-form__footer']//button[text()='Generate Notice']";
	public static String errorMsgSec3 = "//span[@class='tile-error']";
	public static String responsiblePartyTile = "//div[@class='responsible-party-tile-headline']";
	public static String exitBtn = "//button[text()='Exit']";
	public static String generateNoticePopup = "//h1[text()='Generate Notice']";
	public static String cancelNoticeBtn = "//div[@class='case-inspection__notice-action-buttons']/button[1]";
	public static String noticeContent = "//body[@class='mce-content-body ']/p";
	public static String printBtn = "//div[@class='case-inspection__print-notice']//button[text()='Print']";
	public static String doNotPrintBtn = "//div[@class='case-inspection__print-notice']//button[text()='Do Not Print']";
	public static String issueNoticeCIBtn = "//div[@class='case-inspection__notice-action-buttons']/button[2]";
	public static String yesConfirmation = "//div[@class='flex-row--center']/button[text()='Yes']";
	public static String totalContacts = "//div[@class='contact flex-row--center']";
	public static String iframeHTML = "editor_ifr";
	public static String cLP = "//a[text()='Cases']";
	public static String cDP = "//span[@class='checkbox-holder']/following::a[1]";
	public static String addContactsPIP = "(//input[@class='react-autosuggest__input'])[2]";
	public static String crtContactLink2 = "//span[text()='Create a  new contact']";
	public static String nameFieldPIP = "//input[@name='name']";
	public static String crtContactBtn = "//button[text()='Create Contact']";
	public static String followUpInspectionSection = "//h4[text()='Follow-up Inspection' and '1']";
	public static String editFollowUpIcon = "//div[@class='abatement-activities__next_edit']/button";
	public static String editFollowUpPopup = "//div[text()='Edit Follow-up Inspection 1']";
	public static String after7daysDateLink = "//a[text()='After 7 days']";
	public static String updateButton = "//button[text()='Update']";
	public static String scheduleInspectionBtn = "//button[text()='Schedule Inspection']";
	public static String scheduleInspectionPopupBtn = "//div[@class='modal-footer']//button[text()='Schedule Inspection']";
	public static String continueBtnFollowUp = "//div[@class='footer_actions']/button[text()='Continue']";
	public static String continueBtnFollowUp2 = "(//button[text()='Continue'])[2]";
	public static String inspectVioSection = "(//div[@class='progressive-form__title']/h2)[1]";
	public static String arrowForPINote = "//div[@class='abatement-activities__inspection-info']/span";
	public static String inspectionNoteCDP = "//label[@class='inspection-note__label']/following-sibling::p";
	public static String caseNotesIcon = "(//button[@class='attach-btn btn btn-primary'])[2]";
	public static String caseNotePopupValidate = "//div[text()='Add Case Note']";
	public static String noticePopupCancel = "//button[text()='Cancel']";
	public static String validationMessage = "//label[@title='Add Case Note']/../../span";
	public static String noteTextArea = "//textarea[@name='caseNote']";
	public static String notes5000valMsg = "//span[text()='5000 character limit.']";
	public static String createNoteButton = "//button[text()='Create Note']";
	public static String createdNotesTitle = "//div[@id='case-notes']//h2/span";
	public static String newNoticeToggle = "//button[text()='New Notice']";
}
